Repository rodjek/rspec-puppet, pull requests merged in 2018-10, with the labels that each got.

#725 Add Puppet 6 to test matrices
  .travis.yml
  appveyor.yml
Labels: maintenance

#727 2.7.0 release
  CHANGELOG.md
  docs/changelog/index.md
  docs/documentation/configuration/index.md
  rspec-puppet.gemspec
Labels: release-pr

#723 Document execute() methode for function test
  README.md
Labels: documentation

#729 2.7.1 release
  CHANGELOG.md
  docs/changelog/index.md
  rspec-puppet.gemspec
Labels: release-pr
