Repository rodjek/rspec-puppet, pull requests merged in 2018-06, with the labels that each got.

#693 (#669) Filter default resources from catalogue in have_resource_count matcher
  lib/rspec-puppet/matchers/count_generic.rb
  spec/classes/test_empty_class_spec.rb
  spec/fixtures/modules/test/manifests/empty_class.pp
Labels: bugfix

#687 (#670) Increase weight of stubbed facts for Facter 3.x
  .travis.yml
  Gemfile
  appveyor.yml
  lib/rspec-puppet/support.rb
Labels: bugfix

#694 Stub Selinux.is_selinux_enabled to return 0
  lib/rspec-puppet.rb
Labels: enhancement

#667 fix Puppet 3 map/reduce
  lib/rspec-puppet/setup.rb
  spec/classes/map_reduce_spec.rb
  spec/fixtures/modules/map_reduce/manifests/init.pp
  spec/spec_helper.rb
Labels: bugfix

#695 Expecting undef parameters with only_with should not affect expected parameter count
  lib/rspec-puppet/matchers/create_generic.rb
  spec/classes/undef_spec.rb
Labels: bugfix

#696 2.6.12 release
  CHANGELOG.md
  docs/changelog/index.md
  lib/rspec-puppet/tasks/release_test.rb
  rspec-puppet.gemspec
Labels: release-pr

#697 trusted_server_facts requires Puppet >= 4.1.0
  lib/rspec-puppet/adapters.rb
Labels: bugfix

#704 Add basic netlify config
  netlify.toml
Labels: documentation, maintenance

#705 Typo: missing ?
  lib/rspec-puppet/setup.rb
Labels: bugfix
