Repository rodjek/rspec-puppet, pull requests merged in 2018-03, with the labels that each got.

#654 Clarify what can be set with trusted_facts
  docs/_includes/facts_inputs.md
Labels: documentation

#652 (#615) Ensure resource under test is marked as covered
  lib/rspec-puppet/coverage.rb
Labels: bugfix

#656 2.6.10 release
  CHANGELOG.md
  rspec-puppet.gemspec
Labels: release-pr

#657 Add 2.6.10 changelog to website
  docs/changelog/index.md
Labels: documentation

#660 2.6.11 release
  CHANGELOG.md
  docs/changelog/index.md
  rspec-puppet.gemspec
Labels: release-pr

#671 Puppet 6.x (i.e. #master) requires Ruby >= 2.3.0
  .travis.yml
Labels: maintenance
