Repository rodjek/rspec-puppet, pull requests merged in 2020-11, with the labels that each got.

#811 Adjust raise_error to allow rspec-expectation's 3.10.0 changes
  lib/rspec-puppet/matchers/raise_error.rb
Labels: bug

#809 Allow customizing module-layer Hiera configuration
  docs/documentation/configuration/index.md
  lib/rspec-puppet.rb
  lib/rspec-puppet/monkey_patches.rb
  lib/rspec-puppet/support.rb
  spec/classes/hiera_integration_spec.rb
  spec/fixtures/hieradata/common.yaml
  spec/fixtures/modules/hiera_test/data/common.yaml
  spec/fixtures/modules/hiera_test/hiera.yaml
  spec/fixtures/modules/hiera_test/manifests/init.pp
  spec/fixtures/modules/hiera_test/spec/data/common.yaml
  spec/fixtures/modules/hiera_test/spec/hiera.yaml
  spec/fixtures/modules/hiera_test/spec/module_hiera.yaml
  spec/fixtures/modules/hiera_test2/data/common.yaml
  spec/fixtures/modules/hiera_test2/hiera.yaml
  spec/fixtures/modules/hiera_test2/manifests/init.pp
Labels: documentation, feature

#814 (MAINT) Release prep for 2.8.0 release
  CHANGELOG.md
  docs/changelog/index.md
  rspec-puppet.gemspec
Labels: maintenance

#815 (MAINT) Bump version to 2.9.0.pre
  rspec-puppet.gemspec
Labels: maintenance

#812 Add missing links for keep-a-changelog-ish diffs
  CHANGELOG.md
Labels: documentation

#716 Improve self test coverage
  .gitignore
  Gemfile
  Rakefile
  lib/rspec-puppet/matchers/count_generic.rb
  lib/rspec-puppet/matchers/include_class.rb
  spec/classes/test_classes_used_spec.rb
  spec/spec_helper.rb
  spec/spec_helper_unit.rb
  spec/unit/matchers/count_generic_spec.rb
  spec/unit/matchers/have_class_count_spec.rb
  spec/unit/matchers/have_resource_count_spec.rb
  spec/unit/matchers/include_class_spec.rb
  spec/unit/matchers/run_spec.rb
  spec/unit/raw_string_spec.rb
Labels: maintenance
